
services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  carprice-scraper:
    build:
      context: ./carprice-scraper
    volumes:
      - ./carprice-scraper:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    command: python main.py

  carprice-processor:
    build:
      context: ./carprice-processor
    volumes:
      - ./carprice-processor:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    env_file:
      - .env

volumes:
  pgdata:
